accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blogs/urls.py
from django.urls import path
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

urlpatterns = [
    path("", BlogListView.as_view(), name="blogs"),
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include  # new

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),  # New
    path("accounts/", include("accounts.urls")),  # New
    path("", include("pages.urls")),  # new
    path("posts/", include("posts.urls")),  # new
    path("blogs/", include("blogs.urls")),  # new
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

posts/urls.py
from django.urls import path
from .views import PostPageView

urlpatterns = [
    path("", PostPageView.as_view(), name="posts"),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class PostBlog(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"pk": self.pk})

posts/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text[:50]

accounts/views.py
from django.shortcuts import render

from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy


# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blogs/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy
from .models import PostBlog


# Create your views here.
class BlogListView(ListView):
    model = PostBlog
    template_name = "blogs.html"


class BlogDetailView(DetailView):
    model = PostBlog
    template_name = "post_detail.html"


class BlogCreateView(CreateView):
    model = PostBlog
    template_name = "post_new.html"
    fields = ["title", "author", "body"]


class BlogUpdateView(UpdateView):
    model = PostBlog
    template_name = "post_update.html"
    fields = ["title", "body"]


class BlogDeleteView(DeleteView):
    model = PostBlog
    template_name = "post_delete.html"
    success_url = reverse_lazy("blogs")

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"

posts/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Post


# Create your views here.
class PostPageView(ListView):
    model = Post
    template_name = "posts.html"

templates/about.html
{% extends 'base.html' %}
{% block content %}
  <h1>About page</h1>
{% endblock %}

templates/base.html
{% load static %}
<html>
  <head>
    <title>Django project</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  </head>
</html>
{% if user.is_authenticated %}
  <header>
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'about' %}">About</a>
    <a href="{% url 'posts' %}">Posts</a>
    <a href="{% url 'blogs' %}">Blogs</a>
  </header>
  <h1>Hi {{ user.username }}</h1>
  <p>
    <a href="{% url 'logout' %}">Logout</a>
  </p>
  {% block content %}

  {% endblock %}
{% else %}
  <p>Your are not logged in</p>
  <a href="{% url 'login' %}">Login</a> |
  <a href="{% url 'signup' %}">Sign up</a>
{% endif %}

templates/blogs.html
{% extends 'base.html' %}
{% block content %}
  <div class="nav-left">
    <h1><a href="{% url 'post_new' %}">New Blog post</a></h1>
  </div>
  {% for post in postblog_list %}
    <div class="post-entry">
      <h2><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
      <p>{{ post.body }}</p>
    </div>
  {% endfor %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
  <h1>Home page</h1>
{% endblock %}

templates/post_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Post</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure want to delete "{{ object.title }}"?</p>
    <input type="submit" value="Confirm" />
  </form>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="post-entry">
    <h2>{{ object.title }}</h2>
    <p>{{ object.body }}</p>
  </div>
  <a href="{% url 'post_edit' object.pk %}">Edit Blog post</a>
  <a href="{% url 'post_delete' object.pk %}">Delete Blog post</a>
{% endblock %}

templates/post_new.html
{% extends 'base.html' %}
{% block content %}
  <h1>New post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
  </form>
{% endblock %}

templates/post_update.html
{% extends 'base.html' %}
{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="update" />
  </form>
{% endblock %}

templates/posts.html
{% extends 'base.html' %}
{% block content %}
  <ul>
    {% for post in post_list %}
      <li>{{ post.text }}</li>
    {% endfor %}
  </ul>
{% endblock %}